param(
    [ValidateSet('Init','DbUp','Migrate','ResetTest','ExternalizeSources','Api','Web','Harness','DbGuards','DbDown','VerifySql','DbStatus')]
    [string]$Task = 'DbStatus',
    [ValidateSet('docker','native')][string]$Mode,
    [switch]$TestDatabase,
    [ValidateSet('all','scope','offers','adaptive','control-surface')][string]$HarnessSlice = 'all'
)
$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path $PSScriptRoot -Parent
Set-Location -LiteralPath $projectRoot
New-Item -ItemType Directory -Force '.local' | Out-Null

function Assert-Exit([string]$Description) {
    if ($LASTEXITCODE -ne 0) { throw "$Description failed (exit $LASTEXITCODE)." }
}
function New-Secret { return [Convert]::ToHexString([Security.Cryptography.RandomNumberGenerator]::GetBytes(32)).ToLowerInvariant() }
if ($Task -eq 'Init') {
    if (Test-Path -LiteralPath '.env') { Write-Host '.env already exists; preserving credentials.'; exit 0 }
    if (-not $Mode) { $Mode = 'docker' }
    @(
        '# Local-only credentials. Never commit this file.'
        "GRIMOIRE_DB_MODE=$Mode"
        'PGPORT=55432'
        "POSTGRES_PASSWORD=$(New-Secret)"
        "INTAKE_DB_PASSWORD=$(New-Secret)"
        "GRIMOIRE_TOKEN_A=$(New-Secret)"
        "GRIMOIRE_TOKEN_B=$(New-Secret)"
        "GRIMOIRE_TOKEN_REVIEWER_A=$(New-Secret)"
        "GRIMOIRE_TOKEN_AGENT_A=$(New-Secret)"
    ) | Set-Content -LiteralPath '.env' -Encoding utf8
    Write-Host 'Created .env with fresh local database and Handler credentials.'
    exit 0
}
function Verify-Sql {
    $checksums = Get-Content -LiteralPath 'db/gg40/checksums.json' -Raw | ConvertFrom-Json
    foreach ($entry in $checksums.PSObject.Properties) {
        $actual = (Get-FileHash -LiteralPath (Join-Path 'db/gg40' $entry.Name) -Algorithm SHA256).Hash.ToLowerInvariant()
        if ($actual -ne $entry.Value) { throw "Accepted SQL hash mismatch: $($entry.Name)" }
        Write-Host "SHA256 PASS $($entry.Name)"
    }
}
if ($Task -eq 'VerifySql') { Verify-Sql; exit 0 }
if (-not (Test-Path -LiteralPath '.env')) { throw 'Run pwsh -File scripts/dev.ps1 -Task Init first.' }
$config = @{}
foreach ($line in Get-Content -LiteralPath '.env') {
    if ($line -match '^([A-Z_]+)=(.*)$') { $config[$Matches[1]] = $Matches[2] }
}
# Add separate local test identities without replacing existing credentials.
if ($Task -in @('Migrate','ResetTest')) {
    $missingKeys = @('GRIMOIRE_TOKEN_REVIEWER_A','GRIMOIRE_TOKEN_AGENT_A') | Where-Object { -not $config.ContainsKey($_) }
    if ($missingKeys.Count -gt 0) {
        Copy-Item -LiteralPath '.env' -Destination (Join-Path '.local' ('env-before-scope-' + [DateTime]::UtcNow.ToString('yyyyMMddHHmmssfff') + '.bak'))
        foreach ($key in $missingKeys) {
            $config[$key] = New-Secret
            Add-Content -LiteralPath '.env' -Value "$key=$($config[$key])" -Encoding utf8
        }
        Write-Host 'Added separate synthetic reviewer and proposal-agent credentials; preserved existing .env values.'
    }
}
if (-not $Mode) { $Mode = $config.GRIMOIRE_DB_MODE }
$pgPort = [int]$config.PGPORT
if ($pgPort -lt 1024 -or $pgPort -gt 65535) { throw 'Invalid PGPORT.' }
# Locally generated hex credentials can be safely inserted into the provisioning SQL.
foreach ($key in @('POSTGRES_PASSWORD','INTAKE_DB_PASSWORD','GRIMOIRE_TOKEN_A','GRIMOIRE_TOKEN_B')) {
    if ($config[$key] -notmatch '^[a-f0-9]{64}$') { throw "$key must be 64 lowercase hex characters generated by Init." }
}
$env:PGPASSWORD = $config.POSTGRES_PASSWORD
$env:PGCLIENTENCODING = 'UTF8'
$nativeBin = Join-Path $projectRoot '.tools/pgsql/bin'
function Invoke-Psql {
    param([string]$Database = 'postgres', [string]$Sql, [string]$File, [switch]$AsMigrator, [switch]$Scalar)
    $arguments = @('-X','-v','ON_ERROR_STOP=1','-U','postgres','-d',$Database)
    if ($Scalar) { $arguments += @('-A','-t','-q') }
    if ($AsMigrator) { $arguments += @('-c','SET ROLE grimoire_migrator;') }
    if ($Sql) { $arguments += @('-c',$Sql) }
    if ($File) {
        if ($Mode -eq 'docker') {
            $resolvedFile = (Resolve-Path -LiteralPath $File).Path
            if (-not $resolvedFile.StartsWith($projectRoot + [IO.Path]::DirectorySeparatorChar)) { throw 'SQL file outside project.' }
            $relativeFile = $resolvedFile.Substring($projectRoot.Length + 1).Replace('\','/')
            if ($relativeFile.StartsWith('.local/')) { $relativeFile = 'local/' + $relativeFile.Substring(7) }
            $arguments += @('-f',"/workspace/$relativeFile")
        } else { $arguments += @('-f',(Resolve-Path -LiteralPath $File).Path) }
    }
    if ($Mode -eq 'docker') { & docker compose exec -T -e "PGPASSWORD=$($config.POSTGRES_PASSWORD)" db psql @arguments }
    else { & (Join-Path $nativeBin 'psql.exe') -h 127.0.0.1 -p $pgPort @arguments }
    Assert-Exit 'PostgreSQL command'
}
function Provision-Cluster {
    $sql = @'
DO $$ BEGIN
 IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='grimoire_migrator') THEN CREATE ROLE grimoire_migrator NOLOGIN NOSUPERUSER NOCREATEROLE NOCREATEDB NOBYPASSRLS; END IF;
 IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='grimoire_app') THEN CREATE ROLE grimoire_app NOLOGIN NOSUPERUSER NOCREATEROLE NOCREATEDB NOINHERIT NOBYPASSRLS; END IF;
 IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='grimoire_worker') THEN CREATE ROLE grimoire_worker NOLOGIN NOSUPERUSER NOCREATEROLE NOCREATEDB NOINHERIT NOBYPASSRLS; END IF;
 IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='grimoire_intake_app') THEN CREATE ROLE grimoire_intake_app LOGIN NOSUPERUSER NOCREATEROLE NOCREATEDB NOINHERIT NOBYPASSRLS; END IF;
END $$;
ALTER ROLE grimoire_intake_app PASSWORD '__PASSWORD__';
'@
    $sql.Replace('__PASSWORD__',$config.INTAKE_DB_PASSWORD) | Set-Content -LiteralPath '.local/provision.sql' -Encoding utf8
    Invoke-Psql -File '.local/provision.sql' | Out-Null
}
function Initialize-Database([string]$Database) {
    if ($Database -notin @('grimoire_dev','grimoire_test')) { throw 'Unexpected database target.' }
    Provision-Cluster
    $exists = Invoke-Psql -Scalar -Sql "SELECT 1 FROM pg_database WHERE datname='$Database';"
    if (($exists | Out-String).Trim() -ne '1') {
        Invoke-Psql -Sql "CREATE DATABASE $Database OWNER grimoire_migrator;" | Out-Null
    }
    Invoke-Psql -Database $Database -Sql "REVOKE ALL ON DATABASE $Database FROM PUBLIC; GRANT CONNECT ON DATABASE $Database TO grimoire_intake_app;" | Out-Null
    Verify-Sql
    Invoke-Psql -Database $Database -AsMigrator -Sql 'CREATE TABLE IF NOT EXISTS public.grimoire_schema_migrations (name text PRIMARY KEY, sha256 text NOT NULL, applied_at timestamptz NOT NULL DEFAULT clock_timestamp());' | Out-Null
    foreach ($file in @('db/gg40/0022_grimoire_contract.sql','db/gg40/0023_grimoire_review_corrections.sql','db/intake/0024_intake.sql','db/intake/0025_intake_history_authors.sql','db/intake/0026_intake_sources.sql','db/intake/0027_intake_source_objects.sql','db/intake/0028_intake_scope.sql','db/intake/0029_intake_agent_tasks.sql','db/intake/0030_scope_chain_guard.sql','db/intake/0031_worker_controls.sql','db/intake/0032_synthetic_offer_comparison.sql','db/intake/0033_offer_review_identity_guards.sql','db/intake/0034_sourcing_authority_gate.sql','db/intake/0038_windows_adaptive_plans.sql','db/intake/0039_windows_approval_lockdown.sql','db/intake/0040_control_surface.sql','db/intake/0041_watchtower_artifact_guards.sql','db/intake/0042_watchtower_task_sources.sql','db/intake/0043_native_agents.sql','db/intake/0044_organization_onboarding.sql','db/intake/0045_handler_registration.sql','db/intake/0046_public_judge_demo.sql','db/intake/0047_google_identity.sql','db/intake/0048_handler_profile.sql')) {
        $name = Split-Path $file -Leaf
        $hash = (Get-FileHash -LiteralPath $file -Algorithm SHA256).Hash.ToLowerInvariant()
        $previous = (Invoke-Psql -Database $Database -Scalar -Sql "SELECT sha256 FROM public.grimoire_schema_migrations WHERE name='$name';" | Out-String).Trim()
        if ($previous) {
            if ($previous -ne $hash) { throw "Applied migration changed: $name. Do not overwrite history." }
            Write-Host "Already applied: $name"
            continue
        }
        Invoke-Psql -Database $Database -AsMigrator -File $file | Out-Null
        Invoke-Psql -Database $Database -AsMigrator -Sql "INSERT INTO public.grimoire_schema_migrations(name,sha256) VALUES ('$name','$hash');" | Out-Null
        Write-Host "Applied $name to $Database as non-login migration owner."
    }
    $seed = Get-Content -LiteralPath 'db/local-handlers.sql' -Raw
    $seed = $seed.Replace('__TOKEN_A__',$config.GRIMOIRE_TOKEN_A).Replace('__TOKEN_B__',$config.GRIMOIRE_TOKEN_B)
    $seed | Set-Content -LiteralPath '.local/handlers.sql' -Encoding utf8
    Invoke-Psql -Database $Database -AsMigrator -File '.local/handlers.sql' | Out-Null
    foreach ($key in @('GRIMOIRE_TOKEN_REVIEWER_A','GRIMOIRE_TOKEN_AGENT_A')) {
        if ($config[$key] -notmatch '^[a-f0-9]{64}$') { throw "$key must be a generated 64-character local credential." }
    }
    $scopeSeed = (Get-Content -LiteralPath 'db/local-scope-actors.sql' -Raw).Replace('__TOKEN_REVIEWER_A__',$config.GRIMOIRE_TOKEN_REVIEWER_A).Replace('__TOKEN_AGENT_A__',$config.GRIMOIRE_TOKEN_AGENT_A)
    $scopeSeed | Set-Content -LiteralPath '.local/scope-actors.sql' -Encoding utf8
    Invoke-Psql -Database $Database -AsMigrator -File '.local/scope-actors.sql' | Out-Null
    Write-Host "Local Handler identities ready in $Database. Credentials remain in .env."
}

switch ($Task) {
    'DbUp' {
        if ($Mode -eq 'docker') {
            & docker compose up -d --wait db
            Assert-Exit 'Docker PostgreSQL startup'
        } else {
            if (-not (Test-Path -LiteralPath (Join-Path $nativeBin 'initdb.exe'))) { throw 'Run scripts/install-local-tools.ps1 -Postgres first.' }
            $cluster = Join-Path $projectRoot '.local/pgdata'
            if (-not (Test-Path -LiteralPath (Join-Path $cluster 'PG_VERSION'))) {
                $config.POSTGRES_PASSWORD | Set-Content -LiteralPath '.local/pg-password' -Encoding ascii
                $passwordFile = Join-Path $projectRoot '.local/pg-password'
                & (Join-Path $nativeBin 'initdb.exe') -D $cluster -U postgres -E UTF8 --locale=C --auth=scram-sha-256 --pwfile $passwordFile
                Assert-Exit 'PostgreSQL cluster initialization'
                Remove-Item -LiteralPath (Join-Path $projectRoot '.local/pg-password')
            }
            & (Join-Path $nativeBin 'pg_ctl.exe') -D $cluster status *> $null
            if ($LASTEXITCODE -ne 0) {
                $startArgs = @('-D', $cluster, '-l', (Join-Path $projectRoot '.local/postgres.log'), '-o', "`"-h 127.0.0.1 -p $pgPort`"", '-w', 'start')
                $starter = Start-Process -FilePath (Join-Path $nativeBin 'pg_ctl.exe') -ArgumentList $startArgs -WindowStyle Hidden -PassThru
                if (-not $starter.WaitForExit(60000)) { throw 'PostgreSQL startup timed out; inspect .local/postgres.log.' }
                if ($starter.ExitCode -ne 0) { throw 'PostgreSQL startup failed; inspect .local/postgres.log.' }
            }
        }
        Invoke-Psql -Sql 'SELECT version();'
    }
    'Migrate' { Initialize-Database $(if ($TestDatabase) { 'grimoire_test' } else { 'grimoire_dev' }) }
    'ResetTest' {
        # Fixed disposable target only. Never remove the development volume/cluster.
        Provision-Cluster
        Invoke-Psql -Sql 'DROP DATABASE IF EXISTS grimoire_test WITH (FORCE);' | Out-Null
        Initialize-Database 'grimoire_test'
        Invoke-Psql -Database 'grimoire_test' -AsMigrator -File 'db/gg40/fixture_one_case_two_event.sql' | Out-Null
        Write-Host 'Disposable grimoire_test reset; supplied synthetic fixture applied ONLY here.'
    }
    'ExternalizeSources' {
        & (Join-Path $PSScriptRoot 'storage.ps1') -Task Environment -TestDatabase:$TestDatabase
        $dbName = if ($TestDatabase) { 'grimoire_test' } else { 'grimoire_dev' }
        $previousDatabaseUrl = $env:DATABASE_URL
        try {
            # Authenticate locally as postgres, then select the existing NOLOGIN migration owner.
            # The externalizer verifies current_user before its one-time legacy byte transfer.
            $env:DATABASE_URL = "postgres://postgres:$($config.POSTGRES_PASSWORD)@127.0.0.1:$pgPort/${dbName}?options=-c%20role%3Dgrimoire_migrator"
            & cargo run --manifest-path api/Cargo.toml -- externalize-sources
            Assert-Exit 'Existing synthetic source externalization'
        } finally { $env:DATABASE_URL = $previousDatabaseUrl }
    }
    'Api' {
        & (Join-Path $PSScriptRoot 'storage.ps1') -Task Environment -TestDatabase:$TestDatabase
        foreach ($setting in @('GRIMOIRE_GOOGLE_CLIENT_ID','GRIMOIRE_COOKIE_SECURE')) {
            if (-not [Environment]::GetEnvironmentVariable($setting, 'Process') -and $config.ContainsKey($setting)) {
                [Environment]::SetEnvironmentVariable($setting, $config[$setting], 'Process')
            }
        }
        $dbName = if ($TestDatabase) { 'grimoire_test' } else { 'grimoire_dev' }
        $env:DATABASE_URL = "postgres://grimoire_intake_app:$($config.INTAKE_DB_PASSWORD)@127.0.0.1:$pgPort/$dbName"
        $env:GRIMOIRE_BIND = '127.0.0.1:8080'
        & cargo run --manifest-path api/Cargo.toml
        Assert-Exit 'Rust API'
    }
    'Web' {
        Set-Location -LiteralPath (Join-Path $projectRoot 'web')
        & npm.cmd run dev -- --host 127.0.0.1
        Assert-Exit 'Web development server'
    }
    'Harness' {
        & (Join-Path $PSScriptRoot 'storage.ps1') -Task Environment -TestDatabase -ForHarness
        $go = if (Get-Command go -ErrorAction SilentlyContinue) { (Get-Command go).Source } else { Join-Path $projectRoot '.tools/go/bin/go.exe' }
        if (-not (Test-Path -LiteralPath $go)) { throw 'Go unavailable. Run scripts/install-local-tools.ps1 -Go first. Harness unexecuted.' }
        & cargo build --manifest-path api/Cargo.toml
        Assert-Exit 'Rust API build'
        $env:DATABASE_URL = "postgres://grimoire_intake_app:$($config.INTAKE_DB_PASSWORD)@127.0.0.1:$pgPort/grimoire_test"
        $env:GRIMOIRE_TOKEN_A = $config.GRIMOIRE_TOKEN_A
        $env:GRIMOIRE_TOKEN_B = $config.GRIMOIRE_TOKEN_B
        $env:GRIMOIRE_TOKEN_REVIEWER_A = $config.GRIMOIRE_TOKEN_REVIEWER_A
        $env:GRIMOIRE_TOKEN_AGENT_A = $config.GRIMOIRE_TOKEN_AGENT_A
        $apiBinary = Join-Path $projectRoot 'api/target/debug/grimoire-api.exe'
        Set-Location -LiteralPath (Join-Path $projectRoot 'harness')
          $harnessArgs = @('run','.', '-api-binary', $apiBinary)
          if ($HarnessSlice -eq 'scope') { $harnessArgs += '-scope-only' }
          if ($HarnessSlice -eq 'offers') { $harnessArgs += '-offers-only' }
          if ($HarnessSlice -eq 'adaptive') { $harnessArgs += '-adaptive-only' }
          if ($HarnessSlice -eq 'control-surface') { $harnessArgs += '-control-surface-only' }
          & $go @harnessArgs
        Assert-Exit 'Live Go API harness'
    }
    'DbGuards' {
        Invoke-Psql -Database 'grimoire_test' -AsMigrator -File 'api/tests/database_guards.sql'
        Invoke-Psql -Database 'grimoire_test' -AsMigrator -File 'api/tests/source_guards.sql'
          Invoke-Psql -Database 'grimoire_test' -AsMigrator -File 'api/tests/scope_guards.sql'
          Invoke-Psql -Database 'grimoire_test' -AsMigrator -File 'api/tests/worker_guards.sql'
          Invoke-Psql -Database 'grimoire_test' -AsMigrator -File 'api/tests/offer_guards.sql'
          Invoke-Psql -Database 'grimoire_test' -AsMigrator -File 'api/tests/adaptive_guards.sql'
          Invoke-Psql -Database 'grimoire_test' -AsMigrator -File 'api/tests/control_surface_guards.sql'
          Invoke-Psql -Database 'grimoire_test' -AsMigrator -File 'api/tests/native_agent_guards.sql'
          Invoke-Psql -Database 'grimoire_test' -AsMigrator -File 'api/tests/onboarding_guards.sql'
          Invoke-Psql -Database 'grimoire_test' -AsMigrator -File 'api/tests/profile_guards.sql'
          Invoke-Psql -Database 'grimoire_test' -AsMigrator -File 'api/tests/registration_guards.sql'
          Invoke-Psql -Database 'grimoire_test' -AsMigrator -File 'api/tests/google_identity_guards.sql'
    }
    'DbDown' {
        if ($Mode -eq 'docker') { & docker compose stop db; Assert-Exit 'Database stop' }
        else { & (Join-Path $nativeBin 'pg_ctl.exe') -D (Join-Path $projectRoot '.local/pgdata') -m fast -w stop; Assert-Exit 'Database stop' }
    }
    'DbStatus' { Invoke-Psql -Sql 'SELECT version();'; Invoke-Psql -Sql "SELECT datname FROM pg_database WHERE datname IN ('grimoire_dev','grimoire_test');" }
}
