import { useCallback, useEffect, useRef, useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { ApiError, request } from './api';
import { useCaseInvalidation } from './control-api';
import type { Scion } from './api';
import AgentTasks from './AgentTasks';
import { ClaimSelector, useScopeWrite } from './PhysicalScope';
import type { SourceList, SourceSummary } from './evidence-api';
import type { AgentTask, AgentTaskList, ScopeList, ScopeProposal } from './scope-api';
import type { ComparisonBasis, ComparisonInput, ComparisonList, ComparisonProposal, OfferDetail, OfferInput, OfferList, OfferSource, OfferView, SupplierIdentity } from './offers-api';
import './offers.css';

const when = (value: string) => new Date(value).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' });
const failed = (error: unknown) => error instanceof ApiError && error.status === 0 ? 'The API could not be reached. Source-dependent offer content and unsaved forms have been cleared.' : error instanceof Error ? error.message : 'The request failed.';
const accessFailure = (error: unknown) => error instanceof ApiError && ([0, 401, 403, 404].includes(error.status) || error.status >= 500);
const blocked = (proposal: ComparisonProposal) => proposal.status === 'blocked' || proposal.blockers.length > 0 || proposal.content_redacted || !proposal.input || !proposal.snapshot;
const proposalStatus = (proposal: ComparisonProposal) => blocked(proposal) ? proposal.confirmation ? 'Binding blocked · review retained' : 'Comparison blocked' : proposal.confirmation ? 'Synthetic normalization review recorded' : 'Normalization proposed · human review required';
const scopeReady = (proposal: ScopeProposal) => Boolean(proposal.confirmation && proposal.input && proposal.status !== 'blocked' && proposal.blockers.length === 0);
function Failure({ children }: { children: ReactNode }) { return <div className="error-message" role="alert"><div>{children}</div></div>; }
function Missing() { return <span className="offer-missing">Not provided</span>; }
function Value({ value }: { value: string | number | null | undefined }) { return value === null || value === undefined || value === '' ? <Missing /> : <>{value}</>; }
function Reasons({ reasons }: { reasons: string[] }) { return reasons.length > 0 ? <ul className="scope-blockers">{reasons.map((reason, index) => <li key={index}>{reason}</li>)}</ul> : null; }

export default function Offers({ token, scion, canWrite, preferredProposalId, onDirty, onSources, onScopeProposal, onCapabilityProposal }: {
  token: string; scion: Scion; canWrite: boolean; preferredProposalId: string | null; onDirty: (value: boolean) => void; onSources: () => void; onScopeProposal: (id: string) => void; onCapabilityProposal: (id: string) => void;
}) {
  const [offers, setOffers] = useState<OfferView[]>([]); const [comparisons, setComparisons] = useState<ComparisonList | null>(null); const [scope, setScope] = useState<ScopeList | null>(null); const [sources, setSources] = useState<SourceSummary[]>([]); const [tasks, setTasks] = useState<AgentTask[] | null>(null);
  const [taskError, setTaskError] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(true); const [ready, setReady] = useState(false);
  const [selectedOfferId, setSelectedOfferId] = useState<string | null>(null); const [selectedProposalId, setSelectedProposalId] = useState<string | null>(preferredProposalId); const selectedProposalRef = useRef(preferredProposalId);
  const [form, setForm] = useState<'new-offer' | 'edit-offer' | 'comparison' | null>(null); const formRef = useRef(form); formRef.current = form;
  const selectedOfferRef = useRef(selectedOfferId); selectedOfferRef.current = selectedOfferId;
  const generation = useRef(0); const pending = useRef(new Set<AbortController>()); const leaseTimer = useRef<number | undefined>(undefined); const leaseEnd = useRef(0); const dirty = useRef(false);
  const base = `/scions/${scion.id}`;
  const markDirty = useCallback((value: boolean) => { dirty.current = value; onDirty(value); }, [onDirty]);
  const clear = useCallback((reason: string) => {
    generation.current++; pending.current.forEach(controller => controller.abort()); pending.current.clear(); window.clearTimeout(leaseTimer.current); leaseEnd.current = 0;
    setOffers([]); setComparisons(null); setScope(null); setSources([]); setTasks(null); setForm(null); setReady(false); setLoading(false); markDirty(false); setError(reason);
  }, [markDirty]);
  useCaseInvalidation(scion.id, clear);
  const refresh = useCallback(async (force = false) => {
    if (document.visibilityState !== 'visible' || !navigator.onLine) { clear('This tab is hidden or offline. Offer and comparison content and unsaved forms have been cleared.'); return; }
    if (pending.current.size && !force) return;
    if (force) { generation.current++; pending.current.forEach(controller => controller.abort()); pending.current.clear(); }
    const current = generation.current; const started = Date.now();
    const read = async <T,>(path: string): Promise<T> => { const controller = new AbortController(); pending.current.add(controller); const timer = window.setTimeout(() => controller.abort(), 2000); try { return await request<T>(token, path, { cache: 'no-store', signal: controller.signal }); } finally { window.clearTimeout(timer); pending.current.delete(controller); } };
    const [offerResult, comparisonResult, scopeResult, sourceResult, taskResult] = await Promise.allSettled([read<OfferList>(`${base}/offers`), read<ComparisonList>(`${base}/comparisons`), read<ScopeList>(`${base}/scope`), read<SourceList>(`${base}/sources`), read<AgentTaskList>(`${base}/agent-tasks`)]);
    if (current !== generation.current) return;
    const failures = [offerResult, comparisonResult, scopeResult, sourceResult].filter(result => result.status === 'rejected');
    if (failures.length > 0) { clear(failed((failures[0] as PromiseRejectedResult).reason)); return; }
    if (offerResult.status !== 'fulfilled' || comparisonResult.status !== 'fulfilled' || scopeResult.status !== 'fulfilled' || sourceResult.status !== 'fulfilled') return;
    if (Date.now() >= started + 5000 || document.visibilityState !== 'visible' || !navigator.onLine) { clear('Offer access expired. Content and unsaved forms have been cleared.'); return; }
    setOffers(offerResult.value.offers); setComparisons(comparisonResult.value); setScope(scopeResult.value); setSources(sourceResult.value.sources);
    const edited = offerResult.value.offers.find(offer => offer.id === selectedOfferRef.current);
    if (formRef.current === 'edit-offer' && (!edited?.revision.input || edited.revision.content_redacted)) { setForm(null); markDirty(false); }
    if (taskResult.status === 'fulfilled') { setTasks(taskResult.value.tasks); setTaskError(''); } else { setTasks(null); setTaskError('Task queue status could not be read. Bridge connection remains unreported.'); }
    const chosen = comparisonResult.value.proposals.find(proposal => proposal.id === selectedProposalRef.current) ?? comparisonResult.value.proposals[0];
    if (chosen) { selectedProposalRef.current = chosen.id; setSelectedProposalId(chosen.id); }
    setReady(true); setLoading(false); setError(''); leaseEnd.current = started + 5000; window.clearTimeout(leaseTimer.current);
    leaseTimer.current = window.setTimeout(() => { if (Date.now() >= leaseEnd.current) clear('Offer access expired before it could be rechecked. Content and unsaved forms have been cleared.'); }, Math.max(0, leaseEnd.current - Date.now()));
  }, [base, token, clear, markDirty]);
  useEffect(() => {
    void refresh(); const interval = window.setInterval(() => void refresh(), 2000);
    const visibility = () => { if (document.visibilityState !== 'visible') clear('This tab is hidden. Offer and comparison content and unsaved forms have been cleared.'); else void refresh(true); };
    const focus = () => void refresh(); const offline = () => clear('The browser is offline. Offer and comparison content and unsaved forms have been cleared.'); const online = () => void refresh(true); const restored = (event: PageTransitionEvent) => { if (event.persisted) void refresh(true); };
    document.addEventListener('visibilitychange', visibility); window.addEventListener('focus', focus); window.addEventListener('offline', offline); window.addEventListener('online', online); window.addEventListener('pagehide', offline); window.addEventListener('pageshow', restored);
    return () => { generation.current++; pending.current.forEach(controller => controller.abort()); pending.current.clear(); window.clearInterval(interval); window.clearTimeout(leaseTimer.current); leaseEnd.current = 0; onDirty(false); document.removeEventListener('visibilitychange', visibility); window.removeEventListener('focus', focus); window.removeEventListener('offline', offline); window.removeEventListener('online', online); window.removeEventListener('pagehide', offline); window.removeEventListener('pageshow', restored); };
  }, [refresh, clear, onDirty]);
  const epoch = generation.current;
  const selectedOffer = offers.find(offer => offer.id === selectedOfferId); const selectedProposal = comparisons?.proposals.find(proposal => proposal.id === selectedProposalId);
  const qualifiedScopes = scope?.proposals.filter(scopeReady) ?? []; const physical = scion.revision.product_category === 'physical';
  const canRecord = ready && canWrite && physical && qualifiedScopes.length > 0;
  const canCompare = canRecord && comparisons?.can_propose === true && offers.length >= 2;
  function discard() { if (dirty.current && !window.confirm('Discard this unsaved offer or comparison edit?')) return false; markDirty(false); return true; }
  function accessLost() { if (epoch === generation.current) clear('Source access or binding changed. Derived offer content and unsaved forms have been cleared.'); }
  function openProposal(id: string) { if (!discard()) return; setForm(null); selectedProposalRef.current = id; setSelectedProposalId(id); void refresh(true); }
  async function saved(kind: 'offer' | 'comparison' | 'task' | 'confirmation', id?: string) {
    if (epoch !== generation.current || Date.now() >= leaseEnd.current || document.visibilityState !== 'visible' || !navigator.onLine) return;
    setForm(null); markDirty(false);
    if (kind === 'offer' && id) setSelectedOfferId(id);
    if ((kind === 'comparison' || kind === 'confirmation') && id) { selectedProposalRef.current = id; setSelectedProposalId(id); }
    setNotice(kind === 'task' ? 'Candidate queued. A Handler must dispatch it before the local Codex CLI bridge can prepare a proposal.' : kind === 'confirmation' ? 'Synthetic normalization review recorded. No sourcing decision or supplier selection was made.' : kind === 'offer' ? 'Synthetic offer revision saved. Missing commercial fields remain explicit and excluded.' : 'Exact comparison snapshot saved as a normalization proposal for separate human review.');
    await refresh(true);
  }
  return <section className="offers-workspace" aria-label="Synthetic offers and exact comparison"><div className="scope-toolbar"><div><p className="eyebrow">SYNTHETIC COMMERCIAL RECORDS</p><h2>Offers and exact comparison</h2><p>Record explicit synthetic quotations against the confirmed physical chain. Keep missing terms and exclusions visible.</p></div><div className="offer-toolbar-actions"><button className="button secondary" disabled={!canRecord} onClick={() => { if (discard()) setForm('new-offer'); }}>Record synthetic offer</button><button className="button primary" disabled={!canCompare} onClick={() => { if (discard()) setForm('comparison'); }}>Prepare exact comparison</button></div></div>
    <div className="scope-boundary"><strong>Synthetic records only · no supplier contact</strong><p>Two offer revisions are compared on an explicit common basis. A separate enrolled reviewer may confirm normalization. No RFQ, supplier selection, sourcing decision, or commercial approval is produced.</p></div>
    {notice && <div className="success-notice" role="status">{notice}<button aria-label="Dismiss offer notification" onClick={() => setNotice('')}>×</button></div>}{error && <Failure>{error} <button className="text-button" onClick={() => void refresh(true)}>Recheck offer access</button></Failure>}
    {loading ? <div className="loading-panel" role="status">Checking offer, source and physical binding access…</div> : ready && comparisons && scope ? <>
      {!qualifiedScopes.length && <div className="info-notice"><p>A currently usable, separately confirmed synthetic physical scope is required before offer intake. Resolve its blockers in Physical scope first.</p></div>}
      {form === 'new-offer' || form === 'edit-offer' && selectedOffer?.revision.input ? <OfferForm key={form === 'edit-offer' ? `${selectedOffer!.id}-${selectedOffer!.current_revision}` : 'new-offer'} token={token} scion={scion} scopes={qualifiedScopes} sources={sources} initial={form === 'edit-offer' ? selectedOffer : undefined} onDirty={markDirty} onAccessLost={accessLost} onSources={onSources} onCancel={() => { if (discard()) setForm(null); }} onSaved={id => saved('offer', id)} /> : form === 'comparison' ? <ComparisonForm token={token} scion={scion} scopes={qualifiedScopes} offers={offers} queueAvailable={tasks !== null} onDirty={markDirty} onAccessLost={accessLost} onCancel={() => { if (discard()) setForm(null); }} onSaved={(id, queued) => saved(queued ? 'task' : 'comparison', id)} /> : <>
        <section className="scope-card"><div className="section-heading"><h3>Synthetic supplier offers</h3><span className="badge">{offers.length} records</span></div><p className="section-description">Each source, supplier identity and submission revision remains pinned. Incomplete records stay in staging.</p>{offers.length === 0 ? <p className="scope-empty">No synthetic offers recorded. Enter a quotation explicitly; no supplier, price, or commercial term is generated.</p> : <div className="offer-list">{offers.map(offer => { const revision = offer.revision; const input = revision.input; return <button key={offer.id} className={`offer-choice ${offer.id === selectedOfferId ? 'active' : ''}`} aria-pressed={offer.id === selectedOfferId} onClick={() => { if (discard()) setSelectedOfferId(offer.id); }}><strong>{input?.supplier.legal_name || 'Offer content withheld'}</strong><span>{input?.offer_ref || offer.id} · revision {offer.current_revision}</span><span className={revision.blockers.length || revision.content_redacted || revision.missing_fields.length ? 'offer-missing' : ''}>{revision.content_redacted ? 'Access blocked · audit metadata only' : revision.blockers.length ? 'Binding blocked · recorded revision retained' : revision.missing_fields.length ? `Staging · ${revision.missing_fields.length} missing fields` : 'Recorded · comparison is separate'}</span><span>Quoted unit price: <Value value={input?.unit_price} /> {input?.currency || ''}</span></button>; })}</div>}</section>
        {selectedOffer && <OfferRecord key={`${selectedOffer.id}-${selectedOffer.current_revision}`} token={token} scion={scion} offer={selectedOffer} scopes={scope.proposals} canEdit={canRecord && Boolean(selectedOffer.revision.input)} onEdit={() => { if (discard()) setForm('edit-offer'); }} onAccessLost={accessLost} onScope={onScopeProposal} />}
        <section className="scope-card offer-comparisons"><div className="section-heading"><h3>Exact comparison proposals</h3><span className="badge">{comparisons.proposals.length}</span></div><p className="section-description">Two alternatives, one explicitly entered basis. Stored arithmetic is exact decimal; proposals do not select a supplier.</p>{comparisons.proposals.length === 0 ? <p className="scope-empty">No normalization proposed. Record two distinct synthetic suppliers and choose their exact offer revisions.</p> : <div className="offer-proposal-list">{comparisons.proposals.map(proposal => <button className={`scope-proposal-choice ${proposal.id === selectedProposalId ? 'active' : ''}`} key={proposal.id} aria-pressed={proposal.id === selectedProposalId} onClick={() => openProposal(proposal.id)}><strong className={blocked(proposal) ? 'offer-missing' : ''}>{proposalStatus(proposal)}</strong><span>Scion revision {proposal.scion_revision} · {when(proposal.created_at)}</span><code>{proposal.id}</code></button>)}</div>}</section>
        {selectedProposal && <ComparisonRecord key={selectedProposal.id} token={token} scion={scion} proposal={selectedProposal} offers={offers} scopes={scope.proposals} canConfirm={comparisons.can_confirm && selectedProposal.can_confirm_this_proposal} onDirty={markDirty} onAccessLost={accessLost} onSaved={id => saved('confirmation', id)} />}
      </>}
    </> : null}
    <AgentTasks token={token} scionId={scion.id} currentRevision={scion.current_revision} canWrite={canWrite && !form} tasks={tasks} error={taskError} onOpen={(id, kind) => kind === 'prepare_capability_plan' ? onCapabilityProposal(id) : kind === 'prepare_physical_scope' ? onScopeProposal(id) : openProposal(id)} onChanged={() => refresh(true)} />
  </section>;
}

function SourcePin({ source }: { source: OfferSource }) { return <dl className="scope-values offer-source-pin"><dt>Source revision</dt><dd><code>{source.source_id}</code> · revision {source.source_revision}</dd><dt>Handler claim</dt><dd><code>{source.claim_id}</code></dd><dt>Content SHA-256</dt><dd><code>{source.content_sha256}</code></dd><dt>Exact locator</dt><dd>UTF-8 [{source.start_byte}, {source.end_byte}) · end excluded</dd></dl>; }
function ScopePin({ proposal, onOpen }: { proposal?: ScopeProposal; onOpen?: (id: string) => void }) {
  if (!proposal?.confirmation) return <p className="scope-gap">Confirmed physical revision chain unavailable.</p>;
  const confirmation = proposal.confirmation;
  return <details className="revision-details"><summary>Exact confirmed physical revision chain{scopeReady(proposal) ? '' : ' · binding blocked'}</summary><dl><dt>Scope proposal</dt><dd><code>{proposal.id}</code>{onOpen && <button type="button" className="text-button offer-inline-link" onClick={() => onOpen(proposal.id)}>Open physical scope</button>}</dd><dt>Configuration revision</dt><dd><code>{confirmation.configuration_revision_id}</code></dd><dt>Component revision</dt><dd><code>{confirmation.component_revision_id}</code></dd><dt>BOM occurrence revision</dt><dd><code>{confirmation.occurrence_revision_id}</code></dd><dt>Requirement revision</dt><dd><code>{confirmation.requirement_revision_id}</code></dd><dt>Sourcing case revision</dt><dd><code>{confirmation.sourcing_case_revision_id}</code></dd></dl>{!scopeReady(proposal) && <Reasons reasons={proposal.blockers} />}</details>;
}

const supplierFields = [['legal_name', 'Synthetic legal name'], ['jurisdiction', 'Jurisdiction'], ['registration_ref', 'Registration reference'], ['site_code', 'Site code'], ['country_code', 'Country code'], ['account_ref', 'Account reference']] as const;
const commercialFields = [['offered_manufacturer', 'Offered manufacturer'], ['offered_part_number', 'Offered orderable part number'], ['quantity', 'Quoted quantity'], ['uom', 'Unit of measure'], ['unit_price', 'Quoted unit price'], ['currency', 'Currency'], ['destination', 'Destination'], ['incoterm', 'Incoterm'], ['payment_terms', 'Payment terms'], ['quoted_at', 'Quote timestamp · ISO 8601'], ['valid_from', 'Valid from · ISO 8601'], ['valid_until', 'Valid until · ISO 8601'], ['lead_time_days', 'Lead time · whole days']] as const;
type CommercialKey = typeof commercialFields[number][0];

function OfferRecord({ token, scion, offer, scopes, canEdit, onEdit, onAccessLost, onScope }: { token: string; scion: Scion; offer: OfferView; scopes: ScopeProposal[]; canEdit: boolean; onEdit: () => void; onAccessLost: () => void; onScope: (id: string) => void }) {
  const [detail, setDetail] = useState<OfferDetail | null>(null); const [revisionId, setRevisionId] = useState<string | null>(null); const denied = useRef(onAccessLost); denied.current = onAccessLost;
  useEffect(() => {
    let active = true; let controller: AbortController | null = null; let timeout: number | undefined; let lease: number | undefined;
    const read = async () => { if (controller) return; const started = Date.now(); controller = new AbortController(); timeout = window.setTimeout(() => controller?.abort(), 2000); try { const value = await request<OfferDetail>(token, `/scions/${scion.id}/offers/${offer.id}`, { signal: controller.signal, cache: 'no-store' }); if (!active) return; if (Date.now() >= started + 5000 || document.visibilityState !== 'visible' || !navigator.onLine) { setDetail(null); denied.current(); return; } setDetail(value); setRevisionId(previous => previous ?? value.revision.id); window.clearTimeout(lease); lease = window.setTimeout(() => { setDetail(null); denied.current(); }, Math.max(0, started + 5000 - Date.now())); } catch { if (active) { setDetail(null); denied.current(); } } finally { window.clearTimeout(timeout); controller = null; } };
    void read(); const interval = window.setInterval(() => void read(), 2000); return () => { active = false; controller?.abort(); window.clearInterval(interval); window.clearTimeout(timeout); window.clearTimeout(lease); };
  }, [token, scion.id, offer.id]);
  const revision = detail?.revisions.find(item => item.id === revisionId) ?? detail?.revision; const input = offer.revision.content_redacted || offer.revision.input === null ? null : revision?.input;
  return <section className="scope-card offer-record"><div className="section-heading"><h3>{input?.supplier.legal_name || 'Immutable offer history'}</h3><button className="button secondary" disabled={!canEdit} onClick={onEdit}>Edit current offer as new revision</button></div>{!detail || !revision ? <p className="section-description" role="status">Rechecking offer revision history…</p> : <><label className="offer-history-label" htmlFor="offer-history">Immutable submission revision</label><select id="offer-history" value={revision.id} onChange={event => setRevisionId(event.target.value)}>{detail.revisions.map(item => <option key={item.id} value={item.id}>Revision {item.number}{item.number === detail.current_revision ? ' · Current' : ''} · {when(item.created_at)}</option>)}</select><p className="field-help">Submission revision UUID <code>{revision.id}</code></p><Reasons reasons={revision.blockers} />{revision.missing_fields.length > 0 && <><h4 className="offer-subheading">Missing commercial information</h4><Reasons reasons={revision.missing_fields} /><p className="field-help">This revision remains a staging record. Empty commercial fields do not produce a fake governed offer.</p></>}{input ? <><ScopePin proposal={scopes.find(scope => scope.id === input.scope_proposal_id)} onOpen={onScope} /><h4 className="offer-subheading">Pinned supplier identity</h4><dl className="scope-values">{supplierFields.map(([key, label]) => <div className="offer-dl-pair" key={key}><dt>{label}</dt><dd>{input.supplier[key]}</dd></div>)}</dl><h4 className="offer-subheading">Quoted commercial terms · Handler-entered</h4><dl className="scope-values"><dt>Offer reference</dt><dd>{input.offer_ref}</dd><dt>Identity match</dt><dd>{input.identity_match}</dd>{commercialFields.map(([key, label]) => <div className="offer-dl-pair" key={key}><dt>{label}</dt><dd><Value value={input[key]} /></dd></div>)}</dl><h4 className="offer-subheading">Exact quotation evidence</h4><SourcePin source={input.source} /><p className="field-help">Recorded evidence is unverified. Permission and hash integrity do not establish commercial approval.</p></> : <p className="scope-gap">Offer content is withheld because its evidence is unavailable. Only immutable audit identifiers remain.</p>}<details className="revision-details"><summary>Submission and governed record details</summary><dl><dt>Logical offer ID</dt><dd><code>{offer.id}</code></dd><dt>Recorded by principal</dt><dd><code>{revision.created_by}</code></dd><dt>Recorded</dt><dd>{when(revision.created_at)}</dd><dt>Governed offer revision</dt><dd><code>{revision.governed_offer_revision_id || 'Not allocated · staging'}</code></dd><dt>Governed offer line</dt><dd><code>{revision.governed_offer_line_id || 'Not allocated · staging'}</code></dd><dt>Change summary</dt><dd>{input?.change_summary || 'Content withheld'}</dd></dl></details></>}</section>;
}

function OfferForm({ token, scion, scopes, sources, initial, onDirty, onAccessLost, onSources, onCancel, onSaved }: { token: string; scion: Scion; scopes: ScopeProposal[]; sources: SourceSummary[]; initial?: OfferView; onDirty: (value: boolean) => void; onAccessLost: () => void; onSources: () => void; onCancel: () => void; onSaved: (id: string) => Promise<void> }) {
  const initialInput = initial?.revision.input;
  const [supplier, setSupplier] = useState<SupplierIdentity>(() => initialInput?.supplier ?? { legal_name: '', jurisdiction: '', registration_ref: '', site_code: '', country_code: '', account_ref: '' });
  const [values, setValues] = useState<Record<CommercialKey, string>>(() => Object.fromEntries(commercialFields.map(([key]) => [key, initialInput?.[key] == null ? '' : String(initialInput[key])])) as Record<CommercialKey, string>);
  const [scopeId, setScopeId] = useState(initialInput?.scope_proposal_id ?? ''); const [source, setSource] = useState<OfferSource | null>(initialInput?.source ?? null); const [offerRef, setOfferRef] = useState(initialInput?.offer_ref ?? ''); const [identity, setIdentity] = useState<'' | 'exact' | 'ambiguous'>(initialInput?.identity_match ?? ''); const [summary, setSummary] = useState(''); const [synthetic, setSynthetic] = useState(false); const [busy, setBusy] = useState(false); const [stale, setStale] = useState(false); const [error, setError] = useState(''); const write = useScopeWrite(token);
  const eligible = sources.filter(item => item.synthetic && item.rights_status === 'granted' && item.scion_revision === scion.current_revision && item.claim_count > 0);
  useEffect(() => { if (source && !sources.some(item => item.id === source.source_id && item.current_revision === source.source_revision && item.rights_status === 'granted' && item.scion_revision === scion.current_revision)) onAccessLost(); if (scopeId && !scopes.some(item => item.id === scopeId && scopeReady(item))) onAccessLost(); }, [source, sources, scopeId, scopes, scion.current_revision, onAccessLost]);
  async function save(event: FormEvent) {
    event.preventDefault(); if (busy || stale || !synthetic) return; setError('');
    if (!source || !scopeId || !identity || !offerRef.trim() || !summary.trim() || Object.values(supplier).some(value => !value.trim())) { setError('Record every required supplier identity, confirmed scope, exact source locator, offer reference, identity assessment and change summary.'); return; }
    const lead = values.lead_time_days.trim() ? Number(values.lead_time_days) : null;
    if (lead !== null && (!Number.isInteger(lead) || lead < 0)) { setError('Lead time must be a nonnegative whole number of days or remain blank.'); return; }
    const commercial = Object.fromEntries(commercialFields.filter(([key]) => key !== 'lead_time_days').map(([key]) => [key, values[key].trim() || null])) as Omit<Pick<OfferInput, CommercialKey>, 'lead_time_days'>;
    const input: OfferInput = { synthetic: true, scion_revision: scion.current_revision, scope_proposal_id: scopeId, supplier: Object.fromEntries(Object.entries(supplier).map(([key, value]) => [key, value.trim()])) as SupplierIdentity, source, offer_ref: offerRef.trim(), identity_match: identity, ...commercial, lead_time_days: lead, change_summary: summary.trim() };
    setBusy(true); try { const value = await write<OfferView & { offer_id?: string }>(`/scions/${scion.id}/offers${initial ? `/${initial.id}/revisions` : ''}`, input, initial?.current_revision ?? scion.current_revision); const id = value.id || value.offer_id || initial?.id; if (!id) throw new Error('The API did not return the saved offer identity. Recheck the offer list before retrying.'); await onSaved(id); } catch (failure) { setError(failed(failure)); setStale(failure instanceof ApiError && failure.status === 412); if (accessFailure(failure)) onAccessLost(); } finally { setBusy(false); }
  }
  return <form className="scope-form" onSubmit={save}><fieldset disabled={busy || stale}><section className="scope-card"><h3>{initial ? 'Append a synthetic offer revision' : 'Record a synthetic supplier offer'}</h3><p className="section-description">Supplier identity and quotation evidence are required. Leave unknown commercial values blank; they are stored as missing and remain excluded. No term or price is generated.</p><p className="field-help">Keep this tab visible while editing. Hiding it, losing source access or going offline clears unsaved derived content.</p><label className="scope-attestation"><input type="checkbox" checked={synthetic} onChange={event => { setSynthetic(event.target.checked); onDirty(true); }} required /><span>This supplier identity, quotation and all entered terms are synthetic test data. No supplier was contacted.</span></label><label htmlFor="offer-scope">Exact confirmed physical scope</label><select id="offer-scope" value={scopeId} onChange={event => { setScopeId(event.target.value); onDirty(true); }} required><option value="">Select the confirmed revision chain</option>{scopes.map(scope => <option key={scope.id} value={scope.id}>{scope.input?.case_title} · {scope.id}</option>)}</select>{scopeId && <ScopePin proposal={scopes.find(scope => scope.id === scopeId)} />}</section>
    <section className="scope-card"><h3>Explicit synthetic supplier identity</h3>{initial && <p className="field-help">Supplier identity is fixed for this offer series.</p>}<div className="scope-form-grid">{supplierFields.map(([key, label]) => <div className="scope-field" key={key}><label htmlFor={`offer-supplier-${key}`}>{label}</label><input id={`offer-supplier-${key}`} required value={supplier[key]} readOnly={Boolean(initial)} maxLength={1000} onChange={event => { setSupplier(previous => ({ ...previous, [key]: event.target.value })); onDirty(true); }} /></div>)}</div></section>
    <section className="scope-card"><h3>Offer identity and quotation terms</h3><div className="scope-form-grid"><div className="scope-field"><label htmlFor="offer-reference">Synthetic offer reference · required</label><input id="offer-reference" value={offerRef} onChange={event => { setOfferRef(event.target.value); onDirty(true); }} required maxLength={1000} /></div><div className="scope-field"><label htmlFor="offer-identity">Offered identity assessment · required</label><select id="offer-identity" value={identity} onChange={event => { setIdentity(event.target.value as typeof identity); onDirty(true); }} required><option value="">Choose explicitly</option><option value="exact">Exact identity claimed</option><option value="ambiguous">Ambiguous · remains excluded</option></select></div>{commercialFields.map(([key, label]) => <div className="scope-field" key={key}><label htmlFor={`offer-${key}`}>{label}<span className="optional-label">Blank = missing</span></label><input id={`offer-${key}`} value={values[key]} inputMode={['unit_price', 'quantity', 'lead_time_days'].includes(key) ? 'decimal' : undefined} onChange={event => { setValues(previous => ({ ...previous, [key]: event.target.value })); onDirty(true); }} maxLength={2000} /></div>)}</div><p className="field-help">Timestamp fields use explicit ISO 8601 values with a timezone. Prices and quantities are submitted as decimal strings without browser calculation.</p></section>
    <section className="scope-card"><h3>Supplier's own quotation evidence</h3><p className="section-description">Select a permitted synthetic source and exact unverified Handler claim for this quotation. Different suppliers must cite their own sources.</p>{eligible.length ? <ClaimSelector token={token} scionId={scion.id} sources={eligible} onAccessLost={onAccessLost} singleAssignmentLabel="Use this exact quotation locator" onAssign={({ kind: _kind, ...reference }) => { setSource(reference); onDirty(true); }} /> : <p className="scope-gap">No current permitted synthetic source with a claim is available. <button type="button" className="text-button" onClick={onSources}>Open sources and claims</button></p>}{source ? <SourcePin source={source} /> : <p className="scope-gap">Quotation evidence locator missing.</p>}</section>
    <section className="scope-card"><label htmlFor="offer-summary">Revision change summary · required</label><input id="offer-summary" value={summary} onChange={event => { setSummary(event.target.value); onDirty(true); }} required maxLength={1000} /></section>{error && <Failure>{error}</Failure>}{stale && <p className="scope-gap">The Scion or offer changed. Reopen its current revision before preparing another submission.</p>}<div className="scope-form-actions"><button className="button secondary" type="button" onClick={onCancel}>Cancel</button><button className="button primary" disabled={!synthetic || !source}>{busy ? 'Saving…' : initial ? 'Save new synthetic offer revision' : 'Save synthetic offer'}</button></div></fieldset></form>;
}

const basisFields = [['quantity', 'Comparison quantity'], ['uom', 'Unit of measure'], ['currency', 'Currency'], ['destination', 'Destination'], ['incoterm', 'Incoterm'], ['payment_terms', 'Payment terms'], ['as_of', 'As-of timestamp · ISO 8601'], ['valid_from', 'Required validity from · ISO 8601'], ['valid_until', 'Required validity until · ISO 8601']] as const;
function BasisSnapshot({ basis }: { basis: ComparisonBasis }) { return <dl className="scope-values">{basisFields.map(([key, label]) => <div className="offer-dl-pair" key={key}><dt>{label}</dt><dd>{basis[key]}</dd></div>)}</dl>; }

function ComparisonForm({ token, scion, scopes, offers, queueAvailable, onDirty, onAccessLost, onCancel, onSaved }: { token: string; scion: Scion; scopes: ScopeProposal[]; offers: OfferView[]; queueAvailable: boolean; onDirty: (value: boolean) => void; onAccessLost: () => void; onCancel: () => void; onSaved: (id: string, queued: boolean) => Promise<void> }) {
  const [scopeId, setScopeId] = useState(''); const [offerA, setOfferA] = useState(''); const [offerB, setOfferB] = useState(''); const [basis, setBasis] = useState<ComparisonBasis>({ quantity: '', uom: '', currency: '', destination: '', incoterm: '', payment_terms: '', as_of: '', valid_from: '', valid_until: '' }); const [summary, setSummary] = useState(''); const [synthetic, setSynthetic] = useState(false); const [timeoutSeconds, setTimeoutSeconds] = useState(240); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [stale, setStale] = useState(false); const write = useScopeWrite(token);
  const candidates = offers.filter(offer => offer.revision.input?.scope_proposal_id === scopeId && !offer.revision.content_redacted);
  useEffect(() => { if (scopeId && !scopes.some(scope => scope.id === scopeId && scopeReady(scope))) onAccessLost(); if ([offerA, offerB].some(id => id && !offers.some(offer => offer.revision.id === id && offer.revision.input && !offer.revision.content_redacted))) onAccessLost(); }, [scopeId, scopes, offerA, offerB, offers, onAccessLost]);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (busy || stale || !synthetic) return; setError('');
    if (!scopeId || !offerA || !offerB || offerA === offerB || !summary.trim() || Object.values(basis).some(value => !value.trim())) { setError('Choose two different offer revisions, a confirmed scope, every explicit basis term, and a change summary.'); return; }
    const queued = (event.nativeEvent as SubmitEvent).submitter?.getAttribute('value') === 'queue';
    const input: ComparisonInput = { synthetic: true, scope_proposal_id: scopeId, offer_revision_ids: [offerA, offerB], basis: Object.fromEntries(Object.entries(basis).map(([key, value]) => [key, value.trim()])) as ComparisonBasis, change_summary: summary.trim() };
    setBusy(true); try { const value = await write<ComparisonProposal | AgentTask>(`/scions/${scion.id}/${queued ? 'agent-tasks' : 'comparisons/proposals'}`, queued ? { task_kind: 'prepare_offer_normalization', candidate_proposal: input, timeout_seconds: timeoutSeconds } : input, scion.current_revision); await onSaved(value.id, queued); } catch (failure) { setError(failed(failure)); setStale(failure instanceof ApiError && failure.status === 412); if (accessFailure(failure)) onAccessLost(); } finally { setBusy(false); }
  }
  return <form className="scope-form" onSubmit={submit}><fieldset disabled={busy || stale}><section className="scope-card"><h3>Prepare an exact normalization proposal</h3><p className="section-description">Choose two immutable offer revisions and enter a common basis. Different currency, UOM or commercial terms remain excluded; conversion factors are not invented. The API performs exact decimal arithmetic.</p><p className="field-help">Hiding this tab or losing source access clears unsaved derived content.</p><label className="scope-attestation"><input type="checkbox" required checked={synthetic} onChange={event => { setSynthetic(event.target.checked); onDirty(true); }} /><span>This compares synthetic supplier alternatives only. A proposal does not select a supplier or authorize sourcing.</span></label><label htmlFor="comparison-scope">Exact confirmed physical scope</label><select id="comparison-scope" required value={scopeId} onChange={event => { setScopeId(event.target.value); setOfferA(''); setOfferB(''); onDirty(true); }}><option value="">Select the confirmed scope</option>{scopes.map(scope => <option key={scope.id} value={scope.id}>{scope.input?.case_title} · {scope.id}</option>)}</select>{scopeId && <ScopePin proposal={scopes.find(scope => scope.id === scopeId)} />}</section>
    <section className="scope-card"><h3>Two pinned offer submission revisions</h3><div className="scope-form-grid">{[['a', offerA, setOfferA, offerB], ['b', offerB, setOfferB, offerA]].map(([key, value, setter, other]) => <div className="scope-field" key={key as string}><label htmlFor={`comparison-offer-${key}`}>Alternative {String(key).toUpperCase()} · exact submission revision</label><select id={`comparison-offer-${key}`} required value={value as string} onChange={event => { (setter as (value: string) => void)(event.target.value); onDirty(true); }}><option value="">Choose an explicit offer revision</option>{candidates.filter(offer => offer.revision.id !== other).map(offer => <option key={offer.id} value={offer.revision.id}>{offer.revision.input?.supplier.legal_name} · {offer.revision.input?.offer_ref} · r{offer.current_revision}{offer.revision.missing_fields.length ? ' · incomplete' : ''}</option>)}</select>{value && <p className="field-help">Submission revision UUID <code>{value as string}</code></p>}</div>)}</div><p className="field-help">Incomplete offers may be included to expose their exclusion reasons. Supplier identities and series must be distinct.</p></section>
    <section className="scope-card"><h3>Explicit comparison basis</h3><div className="scope-form-grid">{basisFields.map(([key, label]) => <div className="scope-field" key={key}><label htmlFor={`comparison-${key}`}>{label}</label><input id={`comparison-${key}`} required value={basis[key]} maxLength={2000} onChange={event => { setBasis(previous => ({ ...previous, [key]: event.target.value })); onDirty(true); }} /></div>)}</div><label htmlFor="comparison-summary">Proposal change summary</label><input id="comparison-summary" required value={summary} maxLength={1000} onChange={event => { setSummary(event.target.value); onDirty(true); }} /></section>
    <section className="scope-card"><label htmlFor="normalization-timeout">Local Codex task runtime limit · seconds</label><input id="normalization-timeout" type="number" min={30} max={300} step={1} value={timeoutSeconds} onChange={event => { setTimeoutSeconds(Number(event.target.value)); onDirty(true); }} /><p className="field-help">Used only when queuing. The Codex adapter may update the preparation summary, but cannot change these offer identities, terms or numbers. A Handler dispatches the task separately.</p></section>
    {error && <Failure>{error}</Failure>}{stale && <p className="scope-gap">The intake changed. Reopen current records before preparing a new proposal.</p>}<div className="scope-form-actions"><button className="button secondary" type="button" onClick={onCancel}>Cancel</button><button className="button secondary" type="submit" value="queue" disabled={!synthetic || !queueAvailable}>{busy ? 'Submitting…' : 'Queue with local Codex CLI'}</button><button className="button primary" type="submit" value="direct" disabled={!synthetic}>{busy ? 'Submitting…' : 'Save normalization proposal'}</button></div></fieldset></form>;
}

function ComparisonRecord({ token, scion, proposal, offers, scopes, canConfirm, onDirty, onAccessLost, onSaved }: { token: string; scion: Scion; proposal: ComparisonProposal; offers: OfferView[]; scopes: ScopeProposal[]; canConfirm: boolean; onDirty: (value: boolean) => void; onAccessLost: () => void; onSaved: (id: string) => Promise<void> }) {
  const unavailable = blocked(proposal); const input = proposal.input; const snapshot = proposal.snapshot; const confirmation = proposal.confirmation;
  return <div className="comparison-record"><section className="scope-card"><div className="section-heading"><h3>Exact comparison snapshot</h3><span className={`badge ${unavailable ? 'scope-status-blocked' : ''}`}>{proposalStatus(proposal)}</span></div><p className="section-description">Pinned to Scion revision {proposal.scion_revision} · saved {when(proposal.created_at)}</p><Reasons reasons={proposal.blockers} /><details className="revision-details"><summary>Immutable proposal details</summary><dl><dt>Proposal ID</dt><dd><code>{proposal.id}</code></dd><dt>Prepared by principal</dt><dd><code>{proposal.created_by}</code></dd><dt>Change summary</dt><dd>{input?.change_summary || 'Withheld while evidence is unavailable'}</dd></dl></details>{input && <ScopePin proposal={scopes.find(scope => scope.id === input.scope_proposal_id)} />}</section>
    {input && snapshot ? <><section className="scope-card"><h3>Pinned comparison basis</h3><BasisSnapshot basis={snapshot.basis} /><p className="field-help">Same currency and UOM only. Identity FX is exactly 1; the quoted unit price is preserved. Different bases remain excluded until conversion evidence is separately reviewed.</p></section><div className="comparison-alternatives">{snapshot.lines.map((line, index) => { const supplier = offers.find(offer => offer.id === line.offer_id)?.revision.input?.supplier.legal_name; return <section className="scope-card comparison-line" key={line.offer_revision_id}><p className="eyebrow">ALTERNATIVE {index + 1}</p><div className="section-heading"><h3>{supplier || 'Supplier identity withheld'}</h3><span className={`badge ${line.state === 'excluded' || unavailable ? 'scope-status-blocked' : ''}`}>{line.state === 'excluded' ? 'Excluded' : unavailable ? 'Stored comparable line · binding blocked' : 'Comparable on recorded basis'}</span></div><Reasons reasons={line.exclusion_reasons} /><dl className="scope-values"><dt>Normalized unit price</dt><dd><Value value={line.normalized_unit_price} /> {line.currency || ''}</dd><dt>Extended price for basis quantity</dt><dd><Value value={line.extended_price} /> {line.currency || ''}</dd><dt>Lead time</dt><dd><Value value={line.lead_time_days} />{line.lead_time_days !== null ? ' days' : ''}</dd></dl><details className="revision-details"><summary>Pinned offer and line identifiers</summary><dl><dt>Offer series ID</dt><dd><code>{line.offer_id}</code></dd><dt>Submission revision UUID</dt><dd><code>{line.offer_revision_id}</code></dd><dt>Governed offer line</dt><dd><code>{line.governed_offer_line_id || 'Not allocated · staging exclusion'}</code></dd></dl></details></section>; })}</div><p className="scope-footnote">These are supplier alternatives. Their amounts are not added together and no winner is selected. Exclusions and current binding blockers take precedence over historical comparison state.</p></> : <section className="scope-card"><h3>Comparison content withheld</h3><p className="scope-gap">The proposal input, prices and snapshot are unavailable because source access or integrity could not be established. The prior record has not been rewritten.</p></section>}
    <section className="scope-card scope-review"><p className="eyebrow">SEPARATE HUMAN REVIEW</p><h3>{confirmation ? unavailable ? 'Normalization review retained · binding blocked' : 'Synthetic normalization review recorded' : 'Review this normalization proposal'}</h3><p className="section-description">An independently enrolled synthetic Engineering Reviewer may confirm exact normalization. It does not approve the supplier, quotation, quality, payment, or sourcing decision.</p>{confirmation ? <><dl className="scope-values"><dt>Reviewed by principal</dt><dd><code>{confirmation.confirmed_by}</code></dd><dt>Reviewed</dt><dd>{when(confirmation.confirmed_at)}</dd><dt>Review note</dt><dd>{confirmation.review_note ?? 'Withheld while evidence is unavailable'}</dd><dt>Comparison revision ID</dt><dd><code>{confirmation.comparison_revision_id}</code></dd><dt>Artifact ID</dt><dd><code>{confirmation.artifact_id}</code></dd><dt>Sourcing case revision ID</dt><dd><code>{confirmation.sourcing_case_revision_id}</code></dd><dt>Requirement revision ID</dt><dd><code>{confirmation.requirement_revision_id}</code></dd></dl>{unavailable && <p className="scope-gap">This review remains as an audit record. Its binding is currently blocked.</p>}</> : proposal.reviewer_conflict ? <p className="scope-gap">A different synthetic reviewer must review work you prepared, offers you recorded, or candidates you queued.</p> : !canConfirm ? <p className="scope-gap">This identity is not permitted to confirm this normalization. Separate reviewer enrollment and independence are required.</p> : unavailable ? <p className="scope-gap">Resolve the current blockers before human confirmation.</p> : <NormalizationReview token={token} scion={scion} proposal={proposal} onDirty={onDirty} onAccessLost={onAccessLost} onSaved={onSaved} />}</section>
  </div>;
}

function NormalizationReview({ token, scion, proposal, onDirty, onAccessLost, onSaved }: { token: string; scion: Scion; proposal: ComparisonProposal; onDirty: (value: boolean) => void; onAccessLost: () => void; onSaved: (id: string) => Promise<void> }) {
  const [note, setNote] = useState(''); const [acknowledged, setAcknowledged] = useState(false); const [busy, setBusy] = useState(false); const [stale, setStale] = useState(false); const [error, setError] = useState(''); const write = useScopeWrite(token);
  async function confirm(event: FormEvent) { event.preventDefault(); if (busy || stale || !acknowledged || !note.trim()) return; setBusy(true); setError(''); try { const result = await write<ComparisonProposal>(`/scions/${scion.id}/comparisons/proposals/${proposal.id}/confirm`, { confirm_synthetic_normalization: true, review_note: note.trim() }, scion.current_revision); await onSaved(result.id); } catch (failure) { setError(failed(failure)); setStale(failure instanceof ApiError && failure.status === 412); if (accessFailure(failure)) onAccessLost(); } finally { setBusy(false); } }
  return <form className="scope-confirm-form" onSubmit={confirm}><fieldset disabled={busy || stale}><label htmlFor="normalization-review-note">Independent normalization review rationale</label><textarea id="normalization-review-note" rows={4} required maxLength={4000} value={note} onChange={event => { setNote(event.target.value); onDirty(true); }} /><label className="scope-attestation"><input type="checkbox" checked={acknowledged} onChange={event => { setAcknowledged(event.target.checked); onDirty(true); }} required /><span>I independently reviewed the exact offer revisions, supplier and source pins, basis, decimal amounts, exclusions and current binding. I confirm this synthetic normalization only, without selecting or approving a supplier.</span></label>{error && <Failure>{error}</Failure>}{stale && <p className="scope-gap">The intake changed. Reopen the current case and review its current binding.</p>}<button className="button primary" disabled={!acknowledged || !note.trim()}>{busy ? 'Recording review…' : 'Confirm synthetic normalization'}</button></fieldset></form>;
}
