export const scopeKinds = ['configuration', 'component', 'occurrence', 'requirement'] as const;
export type ScopeKind = typeof scopeKinds[number];
export type ScopeReference = {
  kind: ScopeKind;
  source_id: string;
  source_revision: number;
  claim_id: string;
  content_sha256: string;
  start_byte: number;
  end_byte: number;
};
export type ScopeInput = {
  synthetic: true;
  identity_match: 'exact' | 'ambiguous';
  configuration: { product_code: string; product_name: string; configuration_code: string; specification: Record<string, unknown> };
  component: { internal_part_code: string; manufacturer: string; part_number: string; attributes: Record<string, unknown> };
  occurrence: { path: string; quantity: string; uom: string };
  requirement: { code: string; criteria: Record<string, unknown> };
  case_code: string;
  case_title: string;
  source_claims: ScopeReference[];
  unresolved_gaps: string[];
  change_summary: string;
};
export type ScopeConfirmation = {
  proposal_id: string;
  scion_id: string;
  scion_revision: number;
  configuration_revision_id: string;
  component_revision_id: string;
  occurrence_revision_id: string;
  requirement_revision_id: string;
  sourcing_case_id: string;
  sourcing_case_revision_id: string;
  confirmed_by: string;
  confirmed_at: string;
  review_note: string | null;
  synthetic: true;
};
export type ScopeProposal = {
  id: string;
  scion_id: string;
  scion_revision: number;
  created_by: string;
  created_at: string;
  input: ScopeInput | null;
  blockers: string[];
  confirmation: ScopeConfirmation | null;
  status: 'proposed' | 'blocked' | 'confirmed';
  required_role: 'synthetic_engineering_reviewer';
  reviewer_conflict: boolean;
  can_confirm_this_proposal: boolean;
};
export type ScopeList = {
  proposals: ScopeProposal[];
  can_confirm: boolean;
  can_propose: boolean;
  required_role: 'synthetic_engineering_reviewer';
  synthetic_only: true;
};
export type AgentTask = {
  id: string;
  agent_id: string | null;
  agent_revision: number | null;
  scion_id: string;
  scion_revision: number;
  task_kind: 'prepare_physical_scope' | 'prepare_offer_normalization' | 'prepare_capability_plan' | 'research_public_web';
  adapter: 'codex_cli';
  status: 'queued' | 'dispatched' | 'running' | 'cancel_requested' | 'completed' | 'failed' | 'cancelled';
  proposal_id: string | null;
  failure_code: string | null;
  created_at: string;
  claimed_at: string | null;
  completed_at: string | null;
  attempt: number;
  timeout_seconds: number;
  dispatched_at: string | null;
  cancelled_at: string | null;
  lease_until: string | null;
  provider_run_id: string | null;
  output_sha256: string | null;
};
export type AgentTaskList = { tasks: AgentTask[] };
export type AgentTaskEvent = { id: string; status: AgentTask['status']; attempt: number; principal_id: string; recorded_at: string; details: Record<string, unknown> };
