import { useState } from 'react';
import type { ReactNode } from 'react';
import type { Principal, Scion } from './api';
import type { ControlSurfaceConnection } from './control-api';
import { proposalPath } from './workspace-api';
import type { ProposalSummary, WorkspaceState, useWorkspace } from './workspace-api';

export const pageNames: Record<string, string> = { dashboard: 'Dashboard', inbox: 'Inbox', search: 'Search', proposals: 'Proposals', scions: 'Scions', tasks: 'Agent work', watchtower: 'Watchtower', agents: 'Agents', skills: 'Skills', connectors: 'Connectors', audit: 'Activity' };
const humanize = (text: string) => text.replaceAll('_', ' ');
export const workTime = (value: string | null | undefined) => value ? new Date(value).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' }) : 'Never checked';
export function WorkIcon({ name }: { name: string }) {
  const paths: Record<string, ReactNode> = {
    dashboard: <><rect x="3" y="3" width="7" height="7" rx="1" /><rect x="14" y="3" width="7" height="7" rx="1" /><rect x="3" y="14" width="7" height="7" rx="1" /><rect x="14" y="14" width="7" height="7" rx="1" /></>,
    inbox: <><path d="m3 14 3-10h12l3 10v6H3Z" /><path d="M3 14h5l2 3h4l2-3h5" /></>,
    proposals: <><circle cx="12" cy="12" r="9" /><path d="m8 12 3 3 5-6" /></>,
    scions: <path d="M3 7V4h7l2 3h9v13H3Z" />,
    tasks: <><path d="m4 6 2 2 3-4M12 6h8M4 13l2 2 3-4M12 13h8M12 20h8" /></>,
    watchtower: <><path d="M2 12h4l3-7 6 14 3-7h4" /></>,
    agents: <><circle cx="9" cy="8" r="3" /><path d="M3 21v-3a6 6 0 0 1 12 0v3M16 5a3 3 0 0 1 0 6M18 15a5 5 0 0 1 3 5" /></>,
    instructions: <><path d="M12 5v16M3 3h5a4 4 0 0 1 4 2 4 4 0 0 1 4-2h5v16h-5a4 4 0 0 0-4 2 4 4 0 0 0-4-2H3Z" /></>,
    runtime: <><path d="M3 6h8m4 0h6M3 12h2m4 0h12M3 18h12m4 0h2" /><circle cx="13" cy="6" r="2" /><circle cx="7" cy="12" r="2" /><circle cx="17" cy="18" r="2" /></>,
    permissions: <><path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z" /><path d="m8 12 3 3 5-6" /></>,
    credentials: <><circle cx="8" cy="8" r="5" /><path d="m12 12 9 9m-5-5 3-3m-6 0 3-3" /></>,
    runs: <><circle cx="12" cy="12" r="9" /><path d="m10 8 6 4-6 4Z" /></>,
    usage: <><path d="M4 3v18h17M8 17v-5M13 17V8M18 17V4" /></>,
    skills: <><path d="m12 3 9 5-9 5-9-5ZM3 12l9 5 9-5M3 16l9 5 9-5" /></>,
    connectors: <><path d="m9 5 10 10M7 7l8 8-3 3H7l-3-3v-5ZM16 3l-4 4M21 8l-4 4M4 20l3-3" /></>,
    audit: <><path d="M4 10a8 8 0 1 1 1 8M3 4v7h7M12 7v5l3 2" /></>,
    search: <><circle cx="10" cy="10" r="6" /><path d="m15 15 6 6" /></>,
    new: <><path d="M12 5v14M5 12h14" /></>,
    arrow: <><path d="M5 12h14m-5-5 5 5-5 5" /></>,
    exit: <><path d="M9 3H3v18h6M9 12h12m-5-5 5 5-5 5" /></>,
  };
  return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name] ?? paths.proposals}</svg>;
}
export function WorkStatus({ value }: { value: string }) {
  const label: Record<string, string> = { proposed: 'Needs review', inspect: 'Open record', completed: 'Prepared', permission_checked_on_read: 'Checked on access' };
  const tone = /blocked|stale|failed|revoked/.test(value) ? 'danger' : /healthy|connected|current|available|completed/.test(value) && value !== 'disconnected' && value !== 'unavailable' ? 'good' : /required|pending|proposed|delayed|running|queued/.test(value) ? 'attention' : 'neutral';
  return <span className={`work-status ${tone}`}><i />{label[value] ?? humanize(value)}</span>;
}

export function CompanyNavigation({ principal, data, route, onNavigate, onDisconnect, canWrite }: { principal: Principal; data: WorkspaceState | null; route: string; onNavigate: (route: string) => void; onDisconnect: () => void; canWrite: boolean }) {
  const page = route === '/' ? 'dashboard' : route.split('/')[1];
  const inboxCount = data ? data.reviews.length + data.scions.filter(scion => !scion.revision.decision?.trim()).length : null;
  function item(name: string, count?: number | null) { return <button key={name} title={pageNames[name]} aria-label={pageNames[name]} aria-current={page === name ? 'page' : undefined} className={`company-nav-item ${page === name ? 'active' : ''}`} onClick={() => onNavigate(`/${name}`)}><WorkIcon name={name} /><span>{pageNames[name]}</span>{typeof count === 'number' && count > 0 && <small>{count}</small>}</button>; }
  return <aside className="company-sidebar"><button className="company-brand" onClick={() => onNavigate('/dashboard')} aria-label="Grimoire dashboard"><span className="company-avatar">G</span><span><strong>Grimoire</strong><small>{principal.organization_name}</small></span></button>
    <nav aria-label="Company navigation"><div className="company-nav-group"><button className="company-nav-item" aria-label="New Scion" title="New Scion" disabled={!canWrite} onClick={() => onNavigate('/new')}><WorkIcon name="new" /><span>New Scion</span></button>{item('search')}{item('dashboard')}{item('inbox', inboxCount)}</div>
      <div className="company-nav-group"><h2>Work</h2>{item('proposals')}{item('scions')}{item('tasks')}{item('watchtower')}</div>
      <div className="company-nav-group"><h2>Organization</h2>{item('agents')}{item('skills')}{item('connectors')}{item('audit')}</div>
      {data && data.scions.length > 0 && <div className="company-nav-group company-recents"><h2>Recent Scions</h2>{data.scions.slice(0, 3).map(scion => <button className="company-nav-item" key={scion.id} title={scion.revision.name} onClick={() => onNavigate(`/scions/${scion.id}`)}><span className="work-record-dot" /><span>{scion.revision.name}</span></button>)}</div>}
    </nav><div className="company-user"><span className="company-avatar">{principal.display_name.charAt(0)}</span><span>{principal.display_name}<small>Handler workspace</small></span><button title="Disconnect workspace" aria-label="Disconnect workspace" onClick={onDisconnect}><WorkIcon name="exit" /></button></div></aside>;
}

function Empty({ children }: { children: ReactNode }) { return <div className="work-empty">{children}</div>; }
function PageHeading({ title, description, children }: { title: string; description: string; children?: ReactNode }) { return <div className="work-page-heading"><div><h1>{title}</h1><p>{description}</p></div>{children}</div>; }
function CollectionNote({ count, limit }: { count: number; limit: number }) { return count >= limit ? <p className="work-muted">Showing the most recent {limit} records. Open a Scion for its detailed history.</p> : null; }

export function WorkspacePage({ page, connection, onNavigate, canWrite }: { page: string; connection: ReturnType<typeof useWorkspace>; onNavigate: (route: string) => void; canWrite: boolean }) {
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState(page === 'tasks' ? 'active' : 'all');
  const { data, loading, error, refresh } = connection;
  if (!data) return <section className="work-page"><PageHeading title={pageNames[page] ?? 'Workspace'} description="Organization-scoped Grimoire state" />{loading ? <p role="status">Loading workspace…</p> : <div className="work-empty" role="alert"><h2>Workspace disconnected</h2><p>{error || 'Current access could not be checked. Records are hidden.'}</p><button className="button secondary" onClick={() => void refresh()}>Reconnect</button></div>}</section>;
  const scionName = (id: string) => data.scions.find(scion => scion.id === id)?.revision.name ?? 'Scion';
  const matches = (text: string) => text.toLowerCase().includes(query.toLowerCase());
  const decisions = data.scions.filter(scion => !scion.revision.decision?.trim());
  const attention = data.scions.flatMap(scion => {
    const reviews = data.reviews.filter(review => review.scion_id === scion.id);
    const missingDecision = !scion.revision.decision?.trim();
    if (!reviews.length && !missingDecision) return [];
    return [{ id: scion.id, scionId: scion.id, priority: reviews.length ? 0 : 1,
      status: reviews.length ? 'review required' : 'decision required',
      text: reviews.length ? `${reviews.length} required reviews${missingDecision ? ' · Handler decision missing' : ''}` : 'Record what the Handler needs to decide.',
      route: `/scions/${scion.id}${reviews.length ? '/activity' : ''}` }];
  }).sort((first, second) => first.priority - second.priority);
  const active = data.tasks.filter(task => ['queued', 'dispatched', 'running', 'cancel_requested'].includes(task.status) && !task.blocked && !task.stale);
  const search = (label: string) => <label className="work-search"><WorkIcon name="search" /><input aria-label={label} placeholder={label} value={query} onChange={event => setQuery(event.target.value)} /></label>;
  const tabs = (options: [string, string][]) => <div className="work-filters" role="group" aria-label="Filter records">{options.map(([value, label]) => <button key={value} aria-pressed={filter === value} className={filter === value ? 'selected' : ''} onClick={() => setFilter(value)}>{label}</button>)}</div>;
  const scionRows = (scions: Scion[]) => <div className="work-list">{scions.map(scion => <button className="work-row" key={scion.id} onClick={() => onNavigate(`/scions/${scion.id}`)}><WorkIcon name="scions" /><span className="work-row-body"><strong>{scion.revision.name}</strong><small>{humanize(scion.revision.product_category)} · Revision {scion.current_revision}</small></span><WorkStatus value={!scion.revision.decision?.trim() ? 'decision required' : 'intake draft'} /><time>{workTime(scion.revision.created_at)}</time><WorkIcon name="arrow" /></button>)}</div>;
  const proposalRows = (proposals: ProposalSummary[]) => <div className="work-list">{proposals.map(proposal => <button className="work-row" key={proposal.id} onClick={() => onNavigate(proposalPath(proposal))}><WorkIcon name="proposals" /><span className="work-row-body"><strong>{proposal.title}</strong><small>{scionName(proposal.scion_id)} · r{proposal.scion_revision}</small></span><WorkStatus value={proposal.status} /><time>{workTime(proposal.created_at)}</time><WorkIcon name="arrow" /></button>)}</div>;
  if (page === 'dashboard') return <section className="work-page"><PageHeading title="Dashboard" description="Your organization's Scions, proposed work, and decisions." /><div className="work-metrics">{[{ label: 'Needs your attention', count: decisions.length + data.reviews.length, target: 'inbox' }, { label: 'Recorded proposals', count: data.proposals.length, target: 'proposals' }, { label: 'Active agent work', count: active.length, target: 'tasks' }, { label: 'Scions', count: data.scions.length, target: 'scions' }].map(metric => <button key={metric.target} onClick={() => onNavigate(`/${metric.target}`)}><span>{metric.label}</span><strong>{metric.count}{metric.target === 'proposals' && metric.count >= data.collection_limit ? '+' : ''}</strong><WorkIcon name="arrow" /></button>)}</div>
    <div className="work-dashboard-columns"><section><div className="work-section-title"><h2>Needs attention</h2><button onClick={() => onNavigate('/inbox')}>Open inbox →</button></div>{attention.length ? attention.slice(0, 4).map(item => <button className="work-attention-row" key={item.id} onClick={() => onNavigate(item.route)}><WorkStatus value={item.status} /><strong>{scionName(item.scionId)}</strong><span>{item.text}</span></button>) : <Empty>No outstanding Handler decisions or watch reviews.</Empty>}</section><section><div className="work-section-title"><h2>Workspace health</h2><button onClick={() => onNavigate('/watchtower')}>Watchtower →</button></div><div className="work-health-row"><span>Internal monitoring</span><WorkStatus value={!data.watches.length ? 'pending' : data.watches.every(watch => watch.status === 'healthy') ? 'healthy' : 'delayed'} /></div><div className="work-health-row"><span>Grimoire worker</span><WorkStatus value={data.agent_runtime.status} /></div><div className="work-health-row"><span>External provider monitoring</span><WorkStatus value="unavailable" /></div><p className="work-muted">Agents prepare proposals. Decisions stay with the Handler.</p></section></div><div className="work-section-title"><h2>Recent Scions</h2><button onClick={() => onNavigate('/scions')}>View all →</button></div>{data.scions.length ? scionRows(data.scions.slice(0, 5)) : <Empty>Create a Scion to start organizing a product decision. <button className="text-button" disabled={!canWrite} onClick={() => onNavigate('/new')}>New Scion</button></Empty>}</section>;
  if (page === 'scions' || page === 'search') {
    const found = data.scions.filter(scion => matches(`${scion.revision.name} ${scion.id}`));
    const proposals = data.proposals.filter(proposal => matches(`${proposal.title} ${scionName(proposal.scion_id)} ${proposal.id}`));
    return <section className="work-page"><PageHeading title={pageNames[page]} description={page === 'search' ? 'Find a Scion or proposal in this organization.' : 'One product decision per Scion. Open a record to work on it.'}>{page === 'scions' && <button className="button primary" disabled={!canWrite} onClick={() => onNavigate('/new')}>New Scion</button>}</PageHeading><div className="work-list-toolbar">{search(page === 'scions' ? 'Search Scions' : 'Search workspace')}<span className="work-muted">{found.length} Scions</span></div>{found.length ? scionRows(found) : <Empty>No matching Scions.</Empty>}{page === 'search' && query && <><div className="work-section-title"><h2>Proposals</h2></div>{proposals.length ? proposalRows(proposals) : <Empty>No matching proposals.</Empty>}</>}</section>;
  }
  if (page === 'proposals') {
    const proposals = data.proposals.filter(proposal => matches(`${proposal.title} ${scionName(proposal.scion_id)}`) && (filter === 'all' || proposal.status === filter));
    return <section className="work-page"><PageHeading title="Proposals" description="Prepared work for human review. Not approved decisions." /><div className="work-list-toolbar">{tabs([['all', 'All'], ['proposed', 'Needs review'], ['stale', 'Stale'], ['blocked', 'Blocked']])}{search('Search proposals')}</div>{proposals.length ? proposalRows(proposals) : <Empty>No proposals in this view. Open a Scion to prepare one.</Empty>}<CollectionNote count={data.proposals.length} limit={data.collection_limit} /></section>;
  }
  if (page === 'inbox') return <section className="work-page"><PageHeading title="Inbox" description="Human decisions and review obligations. No automated approvals." /><h2 className="work-group-heading">Handler decisions <span>{decisions.length}</span></h2>{decisions.length ? scionRows(decisions) : <Empty>No missing Handler decisions.</Empty>}<h2 className="work-group-heading">Watchtower reviews <span>{data.reviews.length}</span></h2>{data.reviews.length ? <div className="work-list">{data.reviews.map(review => <button className="work-row" key={review.id} onClick={() => onNavigate(`/scions/${review.scion_id}/activity/${review.id}`)}><WorkIcon name="inbox" /><span className="work-row-body"><strong>{scionName(review.scion_id)}</strong><small>{review.reason}</small></span><WorkStatus value={review.status} /><time>{workTime(review.created_at)}</time><WorkIcon name="arrow" /></button>)}</div> : <Empty>No watch-generated reviews. Scion decision gates still apply.</Empty>}<CollectionNote count={data.reviews.length} limit={data.collection_limit} /></section>;
  if (page === 'tasks') {
    const tasks = data.tasks.filter(task => filter === 'all' || (filter === 'active' ? active.includes(task) : filter === 'blocked' ? task.blocked || task.stale || task.status === 'failed' : task.status === 'completed'));
    return <section className="work-page"><PageHeading title="Agent work" description="Existing Rust tasks. Open a Scion to dispatch, cancel, or inspect a result." />{tabs([['active', 'Active'], ['blocked', 'Blocked'], ['completed', 'Prepared'], ['all', 'All']])}{tasks.length ? <div className="work-list">{tasks.map(task => <button className="work-row" key={task.id} onClick={() => onNavigate(`/scions/${task.scion_id}/agent-work/${task.id}`)}><WorkIcon name="tasks" /><span className="work-row-body"><strong>{humanize(task.task_kind)}</strong><small>{scionName(task.scion_id)} · r{task.scion_revision}</small></span><WorkStatus value={task.blocked ? 'blocked' : task.stale ? 'stale' : task.status} /><time>{workTime(task.created_at)}</time><WorkIcon name="arrow" /></button>)}</div> : <Empty>No {filter === 'all' ? '' : filter} work is recorded.</Empty>}<CollectionNote count={data.tasks.length} limit={data.collection_limit} /></section>;
  }
  if (page === 'watchtower') return <section className="work-page"><PageHeading title="Watchtower" description="Persisted internal monitoring. Server checks continue when this page is closed." /><div className="work-list-toolbar">{search('Filter watched Scions')}<span className="work-muted">3 internal watches per Scion</span></div><div className="work-list">{data.scions.filter(scion => matches(scion.revision.name)).map(scion => {
    const watches = data.watches.filter(watch => watch.scion_id === scion.id); const checked = watches.map(watch => watch.last_successful_check).filter((value): value is string => Boolean(value)).sort();
    const status = watches.length !== 3 || checked.length !== 3 ? 'pending' : watches.every(watch => watch.status === 'healthy') ? 'healthy' : 'delayed';
    return <details className="work-watch" key={scion.id}><summary><WorkIcon name="watchtower" /><strong>{scion.revision.name}</strong><WorkStatus value={status} /><span>Checked {workTime(checked.length === 3 ? checked[0] : null)}</span></summary><div className="work-watch-detail">{watches.map(watch => <div key={watch.id}><span>{humanize(watch.kind)}</span><WorkStatus value={watch.status} /><time>{workTime(watch.last_successful_check)}</time></div>)}<button className="text-button" onClick={() => onNavigate(`/scions/${scion.id}/activity`)}>Open Scion activity →</button></div></details>;
  })}</div>{!data.scions.length && <Empty>No Scions are being watched yet.</Empty>}<p className="work-muted work-endnote">External monitoring is unavailable until an authorized connector implements it. No vendor checks are simulated.</p></section>;

  if (page === 'connectors') return <section className="work-page"><PageHeading title="Connectors" description="Data access available to this organization. Agent runtimes are managed separately." /><div className="work-list">{data.connectors.map(connector => <details className="work-watch" key={connector.id}><summary><WorkIcon name="connectors" /><strong>{connector.name}</strong><WorkStatus value={connector.status} /></summary><p className="work-watch-detail">{connector.description}</p></details>)}<div className="work-row"><WorkIcon name="connectors" /><span className="work-row-body"><strong>External provider connector</strong><small>No authorized provider or monitoring implementation configured.</small></span><WorkStatus value="unavailable" /></div></div></section>;
  return <section className="work-page"><PageHeading title="Activity" description="Auditable internal watch events. Source content is never included here." /><div className="work-list-toolbar">{search('Filter activity')}<span className="work-muted">Newest first</span></div>{data.events.filter(event => matches(`${event.kind} ${scionName(event.scion_id)}`)).map(event => <div className="work-audit-row" key={event.id}><WorkIcon name="audit" /><div><strong>{humanize(event.kind)}</strong><button className="work-link" onClick={() => onNavigate(`/scions/${event.scion_id}/activity`)}>{scionName(event.scion_id)}</button><p>{event.summary}</p><details><summary>Audit reference</summary><code>{event.event_key}</code></details></div><time>{workTime(event.recorded_at)}</time></div>)}{data.events.length === 0 && <Empty>No watch events have been recorded.</Empty>}<CollectionNote count={data.events.length} limit={data.collection_limit} /></section>;
}

export function ScionOverview({ scion, connection, onOpen, onEdit, canWrite }: { scion: Scion; connection: ControlSurfaceConnection; onOpen: (view: string, id?: string) => void; onEdit: () => void; canWrite: boolean }) {
  const { data, error, loading } = connection;
  const proposal = data?.nodes.find(node => node.kind === 'capability_proposal');
  const tasks = data?.operations.tasks.filter(task => ['queued', 'dispatched', 'running', 'cancel_requested'].includes(task.status));
  const sourceNodes = data?.nodes.filter(node => node.kind === 'evidence_source') ?? [];
  return <div className="scion-overview"><div className="scion-story"><section className="scion-brief"><h2>Brief</h2><p>{scion.revision.product_description || 'Describe the product so proposed work has a clear starting point.'}</p></section><section className="scion-decision"><div><WorkStatus value={scion.revision.decision?.trim() ? 'handler provided' : 'decision required'} /><h2>{scion.revision.decision?.trim() ? 'The decision' : 'What do you need to decide?'}</h2><p>{scion.revision.decision || 'Give this Scion a specific decision. Agent work can prepare evidence, but it cannot decide for you.'}</p></div><button className="button secondary" disabled={!canWrite} onClick={onEdit}>{scion.revision.decision ? 'Edit brief' : 'Set decision'} <WorkIcon name="arrow" /></button></section>
    {scion.revision.product_category !== 'digital' && <section><div className="work-section-title"><h2>Physical workflow</h2></div><button className="work-property-link" onClick={() => onOpen('scope')}>Physical scope and engineering review →</button><button className="work-property-link" onClick={() => onOpen('offers')}>Supplier offers and comparison →</button></section>}
    <section><div className="work-section-title"><h2>Latest proposal</h2><button onClick={() => onOpen('proposals')}>View proposals →</button></div>{!data ? <p className="work-muted" role={error ? 'alert' : 'status'}>{loading ? 'Checking current case state…' : 'Case disconnected. Proposal and source state are hidden until rechecked.'}</p> : proposal ? <button className="work-proposal-preview" onClick={() => onOpen('proposals', proposal.id.replace(/^plan:/, ''))}><WorkIcon name="proposals" /><span><strong>Capability plan</strong><small>Prepared by agent · Revision {String(proposal.provenance.scion_revision)}</small></span><WorkStatus value={proposal.stale && proposal.status !== 'blocked' ? 'stale' : proposal.status === 'current' ? 'proposed' : proposal.status} /><WorkIcon name="arrow" /></button> : <Empty>No capability proposal yet. <button className="text-button" onClick={() => onOpen('agent-work')}>Prepare with Codex →</button></Empty>}</section>
    <section><div className="work-section-title"><h2>Evidence</h2><button onClick={() => onOpen('sources')}>Open sources →</button></div>{sourceNodes.length ? sourceNodes.slice(0, 4).map(source => <button className="work-row" key={source.id} onClick={() => onOpen('sources')}><WorkIcon name="connectors" /><span className="work-row-body"><strong>{source.title}</strong><small>Internal Scion source</small></span><WorkStatus value={source.status} /></button>) : <p className="work-muted">{data ? 'No internal sources recorded.' : 'Current source access is not available.'}</p>}</section>
  </div><aside className="scion-properties"><h2>Properties</h2><dl><div><dt>Status</dt><dd><WorkStatus value="intake draft" /></dd></div><div><dt>Product</dt><dd>{humanize(scion.revision.product_category)}</dd></div><div><dt>Revision</dt><dd>{scion.current_revision}</dd></div><div><dt>Human review</dt><dd>Required · no approval</dd></div><div><dt>Agent work</dt><dd><button onClick={() => onOpen('agent-work')}>{data ? `${tasks?.length ?? 0} active tasks` : 'Unavailable'}</button></dd></div><div><dt>Monitoring</dt><dd><WorkStatus value={data?.watchtower.health ?? (loading ? 'checking' : 'disconnected')} /></dd></div><div><dt>Last checked</dt><dd>{data ? workTime(data.watchtower.last_successful_check) : 'Not available'}</dd></div></dl><button className="work-property-link" onClick={() => onOpen('graph')}>View dependency graph <WorkIcon name="arrow" /></button><details className="work-disclosure"><summary>Missing information · {scion.missing_information.length}</summary><ul>{scion.missing_information.map(gap => <li key={gap.field}>{gap.message}</li>)}</ul></details><details className="work-disclosure"><summary>Record identity</summary><code>{scion.id}</code></details></aside></div>;
}

export function ScionActivity({ connection }: { connection: ControlSurfaceConnection }) {
  const { data, error, loading } = connection;
  if (!data) return <Empty>{loading ? 'Checking activity…' : error || 'Case disconnected.'}</Empty>;
  return <section className="work-case-activity"><div className="work-section-title"><h2>Activity</h2><WorkStatus value={data.watchtower.health} /></div><p className="work-muted">Last server check {workTime(data.watchtower.last_successful_check)}</p>{data.operations.events.map(event => <div className="work-audit-row" key={event.id}><WorkIcon name="audit" /><div><strong>{humanize(event.kind)}</strong><p>{event.summary}</p><details><summary>Audit reference</summary><code>{event.event_key}</code></details></div><time>{workTime(event.recorded_at)}</time></div>)}{!data.operations.events.length && <Empty>No watch events recorded.</Empty>}<details className="work-disclosure"><summary>Required watch reviews · {data.operations.human_review.length}</summary>{data.operations.human_review.map(review => <div className="work-audit-row" key={review.id}><WorkStatus value={review.status} /><p>{review.reason}</p><time>{workTime(review.created_at)}</time></div>)}</details></section>;
}
